### ISSUE TITLE
bgpq3 overflow for large as numbers and accepts private as numbers

### ISSUE THREAD

**Issue by htj** [snar/bgpq3#16]
$ bgpq3 -3f1 AS-HURRICANE |tail -n 3
ip as-path access-list NN permit ^1(_[0-9]+)*_(525620|553259|559371|1973394)$
ip as-path access-list NN permit ^1(_[0-9]+)*_(2629023|-94915195|-94914185)$

In as-dot:

$ bgpq3 -D3f1 AS-HURRICANE |tail -n 3
ip as-path access-list NN permit ^1(_[0-9]+)*_(6.752|6.762|6.765|6.845)$
ip as-path access-list NN permit ^1(_[0-9]+)*_(8.1332|8.28971|8.35083|30.7314)$
ip as-path access-list NN permit ^1(_[0-9]+)*_(40.7583|64087.46469|64087.47479)$

$ grep 4200052101 *.db
radb.db:members:    AS38883, AS38887, AS38900, AS38906, AS38911, AS4200052101
radb.db:members:    AS393968, AS393978, AS394061, AS4200052101, AS4200053111
radb.db:members:    AS393968, AS393978, AS394061, AS4200052101, AS4200053111

So AS-HURRICANE added private as numbers to their as-set AFAICT.

The set of private/special as number should probably be filtered out.
http://www.iana.org/assignments/iana-as-numbers-special-registry/iana-as-numbers-special-registry.xhtml

I guess that a signed int/long is used for as numbers. It should probably be an unsigned long.

**Comment by job** [comment]
I created an example as-set for easy testing after hurricane fixes their set:

```
Vurt:~ job$ whois -h rr.ntt.net AS15562:AS-PRIV32BITASN | grep -v remarks
as-set:         AS15562:AS-PRIV32BITASN
descr:          test for bgpq3
members:        AS4200052101
members:        AS4200053111
tech-c:         DUMY-RIPE
admin-c:        DUMY-RIPE
mnt-by:         SNIJDERS-MNT
changed:        unread@ripe.net 20000101
created:        2015-06-16T08:46:36Z
last-modified:  2015-06-16T08:46:36Z
source:         RIPE

Vurt:~ job$ bgpq3 -h rr.ntt.net -j3f1 AS15562:AS-PRIV32BITASN
{"NN": [
  -94915195,-94914185
]}
Vurt:~ job$
```

**Comment by snar** [comment]
On Tue, Jun 16, 2015 at 01:33:46AM -0700, Henrik Thostrup Jensen wrote:
> $ bgpq3 -3f1 AS-HURRICANE |tail -n 3
> ip as-path access-list NN permit ^1([0-9]+)*(525620|553259|559371|1973394)$
> ip as-path access-list NN permit ^1([0-9]+)*(2629023|-94915195|-94914185)$

Thanks for noticing, fixed and uploaded to github.   
 
> The set of private/special as number should probably be filtered out.
> http://www.iana.org/assignments/iana-as-numbers-special-registry/
> iana-as-numbers-special-registry.xhtml

as23456 were already in exclusion list, now all other asns in private
and reserved space are excluded by default too.

> I guess that a signed int/long is used for as numbers. It should probably 
> be an unsigned long.

AS numbers storead as a bitmap, problem was with %i format character
that interpreted numbers > 2^31 as negative integers :( Thanks again.
