### ISSUE TITLE
Support for expanding AS-macro to AS-numbers

### ISSUE THREAD

**Issue by emjemj** [snar/bgpq3#26]
I have a use-case where I would need to expand an AS-Macro into AS-numbers but not further into prefixes, preferably with the JSON output mode.

**Comment by snar** [comment]
On Sun, Sep 04, 2016 at 05:21:12AM -0700, Eric Lindsjö wrote:
> I have a use-case where I would need to expand an AS-Macro into AS-numbers but
> not further into prefixes, preferably with the JSON output mode.

Looks like it can be done as easy as just:

snar@fri:~/compile/bgpq3>./bgpq3 -jf 1 as-eltel
{"NN": [
  112,5495,6857,8377,20597,23456,34102,35357,
  43951,52007
]}

(-j: JSON output, -f NN - as-path filter for 'real routers' (junos/ios/ios-xr)
or just set of AS numbers in json/bird formats. NN is ignored in later case).

Or am I missing something ?

**Comment by emjemj** [comment]
Well, that was easy. Not terribly obvious though.
