### ISSUE TITLE
make -3 the default?

### ISSUE THREAD

**Issue by job** [snar/bgpq3#28]
```
Vurt:~ job$ bgpq3

Usage: bgpq3 [-h host[:port]] [-S sources] [-P|E|G <num>|f <num>] [-2346ABbDJjXd] [-R len] <OBJECTS>...
...
 -3        : assume that your device is asn32-safe
```

Perhaps it is time to make `-3` the default?

**Comment by snar** [comment]
On Mon, Jan 23, 2017 at 01:28:05AM -0800, Job Snijders wrote:
> Vurt:~ job$ bgpq3
> 
> Usage: bgpq3 [-h host[:port]] [-S sources] [-P|E|G <num>|f <num>] [-2346ABbDJjXd] [-R len] <OBJECTS>...
> ...
>  -3        : assume that your device is asn32-safe
> 
> Perhaps it is time to make -3 the default?

Incompatible changes shall not be introduced without at least major version
update. So, when/if bgpq3 v.1 will be released and not before.

**Comment by job** [comment]
ok!
