### ISSUE TITLE
ERROR:Unable to create socket: Address family not supported by protocol family

### ISSUE THREAD

**Issue by alex-belik** [snar/bgpq3#29]
Freebsd 10.3, IPV6 disabled....
bgpq3-master (latest)
How to fix error when running:
ERROR:Unable to create socket: Address family not supported by protocol family

**Comment by snar** [comment]
On Tue, Feb 07, 2017 at 09:47:50PM -0800, alex-belik wrote:
> Freebsd 10.3, IPV6 disabled....
> bgpq3-master (latest)
> How to fix error when running:
> ERROR:Unable to create socket: Address family not supported by protocol family

Wow, looks like whois.radb.net finally got ipv6 :)

Can you try the latest head ?

**Comment by alex-belik** [comment]
yes

**Comment by alex-belik** [comment]
It's works fine! THx
