### ISSUE TITLE
Enable support for outputting Huawei as-path access-lists

### ISSUE THREAD

**Issue by wbergg** [snar/bgpq3#39]
Add support for Huawei devices (-H) to output Huawei as-path access-lists.

Eg.
./bgpq3 -f 39651 AS-COMHEM -H
ip as-path-filter NN permit ^39651(_39651)*$
ip as-path-filter NN permit ^39651(_[0-9]+)*_(25037|28942|56563|59835)$

**Comment by snar** [comment]
On Mon, Aug 06, 2018 at 01:59:57AM -0700, Alexander Wagberg wrote:
> Add support for Huawei devices (-H) to output Huawei as-path access-lists.
> 
> Eg.
> ./bgpq3 -f 39651 AS-COMHEM -H
> ip as-path-filter NN permit ^39651(39651)*$
> ip as-path-filter NN permit ^39651([0-9]+)*_(25037|28942|56563|59835)$

Can you provide link to Huawei documentation, so I can implement
prefix-lists too ?

**Comment by wbergg** [comment]
You need a login to see the documentation, I took a screenshot of both as-path and prefix-lists: https://wberg.com/huawei.png

**Comment by snar** [comment]
On Mon, Aug 06, 2018 at 01:59:57AM -0700, Alexander Wagberg wrote:
> Add support for Huawei devices (-H) to output Huawei as-path access-lists.
> 
> Eg.
> ./bgpq3 -f 39651 AS-COMHEM -H
> ip as-path-filter NN permit ^39651(39651)*$
> ip as-path-filter NN permit ^39651([0-9]+)*_(25037|28942|56563|59835)$

Done, pushed to github head. Two notes: 
- new flag is called -U, not -H
- I'm not sure that removing configuration is done with 'undo' prefix,
can you confirm ? 

Example:

./bgpq3 -Uf 39651 AS-COMHEM
undo ip as-path-filter NN
ip as-path-filter NN permit ^39651(39651)*$
ip as-path-filter NN permit ^39651([0-9]+)*_(25037|28942|56563|59835)$
