### ISSUE TITLE
Clarify Nokia (classic CLI) options

### ISSUE THREAD

**Issue by mfisher128** [snar/bgpq3#53]
Could you clarify the Nokia classic CLI (-N) allowed option combinations?

While it is correct that aggregation and refine (-ARr) are not compatible with Nokia classic CLI [ip|ipv6]-prefix-list, they should be supported with standard prefix-lists.

In other words, only the -E flag is incompatible with -ARr for Nokia classic CLI (-N).

Valid:
./bgpq3 -h localhost -36AN -R 128 -l foo AS8218
prefix-list "foo"
    prefix 2001:67c:25a8::/48 prefix-length-range 48-128
    prefix 2001:1b48::/32 prefix-length-range 32-128
...

Invalid:
./bgpq3 -h localhost -36AEN -R 128 -l foo AS8218

Cli help text for standard prefix-list:
*A:sr7-1.eth>config>router>policy-options>prefix-list# prefix 
  - prefix <ip-prefix/prefix-length> [exact|longer|through <length>|prefix-length-range <length1-length2>]

Thanks!

**Comment by hellt** [comment]
that is correct, prefix length ranges are supported for `prefix-list` in classic CLI, as well as in the MD-CLI as follows:

```
A:admin@VSR# compare
+   prefix 1.0.0.0/24 type range {
+       start-length 12
+       end-length 16
+   }
```

/cc @snar

**Comment by snar** [comment]
Corrected:

./bgpq3 -36AN -R 128 -l foo AS8218
configure router policy-options
begin
no prefix-list "foo"
prefix-list "foo"
    prefix 2001:67c:25a8::/48 prefix-length-range 48-128
    prefix 2001:1b48::/32 prefix-length-range 32-128
    prefix 2a00:1f60::/32 prefix-length-range 32-128
