### ISSUE TITLE
bgpq3 exit code is 255, stderr: b'FATAL ERROR:select timeout\n'

### ISSUE THREAD

**Issue by smaxx1337** [snar/bgpq3#57]
Hello,

we are running bgpq3 in a crontab and sometimes we get this error:
`bgpq3 exit code is 255, stderr: b'FATAL ERROR:select timeout\n'`

It happens randomly, not every time. Is there any reason why? How can I fix this? Do you need more info to see whats going on?

**Comment by snar** [comment]
On Thu, Feb 13, 2020 at 08:56:22PM -0800, smaxx1337 wrote:
> Hello,
> 
> we are running bgpq3 in a crontab and sometimes we get this error:
> bgpq3 exit code is 255, stderr: b'FATAL ERROR:select timeout\n'
> 
> It happens randomly, not every time. Is there any reason why? How can I fix
> this? Do you need more info to see whats going on?

Sorry for delay, it was crazy days here :( 

"FATAL ERROR:select timeout" means that bgpq3 did not received no data
from RADB in ten seconds. Possible reasons: 
- RADB was too slow responding on some query
- heavy packetloss can lead to timeout too.. 

I just increased select timeout to 30 sec and pushed this change to github,
can you please check if it helps ?

**Comment by smaxx1337** [comment]
Hey, thank you very much! I pulled now and let's see if that helps. I'll close this issue for now and re open it if it does occur again.
