### ISSUE TITLE
Rationale behind the recommended sources

### ISSUE THREAD

**Issue by vincentbernat** [snar/bgpq3#61]
Hey!

The documentation says the recommended sources are RIPE, RADB and APNIC. If I test what I get for `AS-HURRICANE`, which is a very large AS-set, I get:

```console
$ bgpq3 -S RIPE,RADB,APNIC AS-HURRICANE | wc -l
712073
```

Without filtering, I get:

```console
$ bgpq3 AS-HURRICANE | wc -l
875980
```
So, more routes than in a full-view. If I add more RIR, I get:

```console
$ bgpq3 -S RIPE,RADB,APNIC,LACNIC,AFRINIC,ARIN AS-HURRICANE | wc -l
802259
```

Each of them contribute a bit (except LAPNIC which doesn't seem to export `route` objects, just `inetnum` with the wrong format). I can also add some random DB and get even more results:

```console
$ bgpq3 -S RIPE,RADB,APNIC,LACNIC,AFRINIC,ARIN,LEVEL3,NTTCOM,ALTDB AS-HURRICANE | wc -l
856987
```

`AS-HURRICANE` may not be the best example but if the documentation could expand a bit on the recommended sources, it would be helpful. Even a link to a presentation explaining that. Why is AFRINIC not here for example? Why not ARIN?

Thanks.

**Comment by snar** [comment]
Documentation was updated some months ago, sorry for not reporting it right then.
