### ISSUE TITLE
Sequence numbers not respected with empty result

### ISSUE THREAD

**Issue by bswinnerton** [snar/bgpq3#64]
On bgpq3 0.1.35, when the `-s` argument is passed and the prefix list ends up being empty, the fallback prefix list does not use sequence numbers.

For example with the command: `$ bgpq3 -S RIPE,ARIN,APNIC,AFRINIC -4 -s -l AS714-IN AS714`:

Expected:

```
no ip prefix-list AS714-IN
! generated prefix-list AS714-IN is empty
ip prefix-list AS714-IN seq 1 deny 0.0.0.0/0
```

Actual:

```
no ip prefix-list AS714-IN
! generated prefix-list AS714-IN is empty
ip prefix-list AS714-IN deny 0.0.0.0/0
```

**Comment by snar** [comment]
Fixed in HEAD, thanks for reporting.
