### ISSUE TITLE
Possibility of tagging a new release

### ISSUE THREAD

**Issue by ggidofalvy-tc** [snar/bgpq3#68]
Hi there,

Could you please tag a new release in the near future? From what I can tell, there have been multiple new features and bugfixes added to bgpq3 since 2018 November, the last time a release was tagged.

It'd make it much easier for package / distribution maintainers to ship a newer, more feature-complete (and more stable) version of bgpq3 if a new release were to be tagged.

Thanks!

**Comment by snar** [comment]
Sure, makes sense. Done.
